# Generated by Django 5.1.4 on 2024-12-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpstracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Lokasi', 'verbose_name_plural': 'Lokasi'},
        ),
        migrations.AddField(
            model_name='location',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
