# Generated by Django 5.1.4 on 2024-12-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpstracker', '0002_alter_location_options_location_last_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Perangkat',
        ),
        migrations.AlterModelOptions(
            name='perangkat',
            options={'verbose_name': 'Perangkat', 'verbose_name_plural': 'Perangkat'},
        ),
    ]
